### ISSUE TITLE
Loading checkpoint shards:   0% 0/2 [00:00<?, ?it/s]^C

### ISSUE THREAD

**Issue by tralala87** [kaleido-lab/dolphin#1] opened 2023-05-07 01:46 UTC
Can't run it on free colab T4 with `# Advice for 1 Tesla T4 15GB
python video_chatgpt.py --load "VideoCaptioning_cuda:0,ImageCaptioning_cuda:0,ModelscopeT2V_cuda:0",`  getting this error:

Loading checkpoint shards:   0% 0/2 [00:00<?, ?it/s]^C

**Comment by tiif** [comment] 2023-06-12 01:27
I also ran into this issue when running 
```python
from modules.blip import ImageCaptioning

tool_blip2 = ImageCaptioning("cpu")
frames_captioning = tool_blip2.inference # input: f"{video_path}", output: caption (str)
```
in inference.py, suspect it is a duplicate of https://github.com/huggingface/transformers/issues/22064

**Comment by fenghora** [comment] 2023-07-23 12:24
Sorry, this was our oversight. When we tried to reproduce this issue using the free Colab T4, it alerted us that we had used all the RAM, resulting in a session crash. Therefore, it may be necessary to use a machine with a larger cache. We have already removed this instruction from the readme.

**Closed as completed** 2023-07-23 12:58 UTC
